apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  server.insecure: "true"
  server.rootpath: ""
  application.instanceLabelKey: argocd.argoproj.io/instance
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-repo-creds-github
  namespace: argocd
data:
  type: git
  url: https://github.com/ROHIT-213/todo-app-devops.git
  password: $GITHUB_TOKEN
  username: $GITHUB_USERNAME
  sshPrivateKeySecret:
    name: github-ssh-key
    key: ssh-privatekey
