apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/YOUR_GITHUB_ORG/todo-app-deployment.git
  password: YOUR_GITHUB_TOKEN
  username: not-used
