# argocd/monitoring-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  source:
    repoURL: https://github.com/ROHIT-213/todo-app-devops.git
    targetRevision: main
    path: Monitoring
    helm:
      valueFiles:
        - values.yaml
      skipCrds: true           # Important to prevent ArgoCD from trying to manage CRDs directly, which can cause sync issues
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    # - group: admissionregistration.k8s.io
    #   kind: MutatingWebhookConfiguration
    #   jqPathExpressions:
    #     - '.webhooks[]?.clientConfig.caBundle'
    # - group: admissionregistration.k8s.io
    #   kind: ValidatingWebhookConfiguration
    #   jqPathExpressions:
    #     - '.webhooks[]?.clientConfig.caBundle'


# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kube-prometheus-stack
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
#   # annotations:
#   #   argocd.argoproj.io/sync-wave: "1"
# spec:
#   project: monitoring
#   # project: default
#   source:
#     repoURL: 'https://prometheus-community.github.io/helm-charts'
#     chart: kube-prometheus-stack
#     targetRevision: 70.4.1
#     helm:
#       values: |
#         alertmanager:
#           alertmanagerSpec:
#             envFrom:
#               - secretRef:
#                   name: monitoring-credentials
#           config:
#             global:
#               resolve_timeout: 5m
#             route:
#               receiver: 'slack-notifications'
#             receivers:
#               - name: 'slack-notifications'
#                 slack_configs:
#                   - channel: '#alerts-devops'
#                     api_url: ${SLACK_WEBHOOK_URL}
#                     send_resolved: true
#         prometheus:
#           prometheusSpec:
#             storageSpec:
#               volumeClaimTemplate:
#                 spec:
#                   storageClassName: gp2
#                   accessModes:
#                     - ReadWriteOnce
#                   resources:
#                     requests:
#                       storage: 10Gi
#         grafana:
#           admin:
#             existingSecret: monitoring-credentials
#             userKey: admin-user
#             passwordKey: grafana-password
#           persistence:
#             enabled: false
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: monitoring
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
#       # - Replace=true

      
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kube-prometheus-stack
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: 'https://prometheus-community.github.io/helm-charts'
#     chart: kube-prometheus-stack
#     targetRevision: 70.4.1    # Uses stable chart track definitions
#     helm:
#       values: |
#         alertmanager:
#           alertmanagerSpec:
#             # --- FIX: Injects your secret keys as system environment variables inside the pod ---
#             envFrom:
#               - secretRef:
#                   name: monitoring-credentials
#           config:
#             global:
#               resolve_timeout: 5m
#             route:
#               receiver: 'slack-notifications'
#             receivers:
#               - name: 'slack-notifications'
#                 slack_configs:
#                   - channel: '#alerts-devops'
#                     api_url: ${SLACK_WEBHOOK_URL}
#                     send_resolved: true
#         prometheus:
#           prometheusSpec:
#             storageSpec:{}
#               # volumeClaimTemplate:
#               #   spec:
#               #     storageClassName: gp2
#               #     accessModes: ["ReadWriteOnce"]
#               #     resources:
#               #       requests:
#               #         storage: 10Gi
#         grafana:
#           persistence:
#             enabled: false # Disable default Grafana deployment since we will deploy it separately with our custom admin credentials
#           admin:
#             # Grafana extracts its admin credentials directly from our secret keys
#             existingSecret: monitoring-credentials
#             userKey: admin-user
#             passwordKey: grafana-password
#           # persistence:
#           #   enabled: true
#           #   storageClassName: gp2
#           #   accessModes: ["ReadWriteOnce"]
#           #   size: 5Gi
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: monitoring
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     # createNamespace: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true # Crucial flag to prevent CRD schema size restriction errors
#       - Replace=true