apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: Monitoring stack applications
  sourceRepos:
    - https://github.com/ROHIT-213/todo-app-devops.git
    - https://github.com/prometheus-operator/prometheus-operator.git
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc       #gemini
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
    # - group: ""
    #   kind: Namespace
    # - group: ""
    #   kind: Service  # Added to allow cross-namespace control plane service endpoints (gemini)
    # - group: apiextensions.k8s.io
    #   kind: CustomResourceDefinition
    # - group: admissionregistration.k8s.io
    #   kind: ValidatingWebhookConfiguration
    # - group: admissionregistration.k8s.io
    #   kind: MutatingWebhookConfiguration
    # - group: rbac.authorization.k8s.io
    #   kind: ClusterRole
    # - group: rbac.authorization.k8s.io
    #   kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"