apiVersion: v1
kind: Secret
metadata:
  name: ecr-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: YOUR_ECR_REGISTRY/helm-charts
  name: ecr
  password: YOUR_AWS_PASSWORD
  username: AWS
